load("@com_github_benchsci_rules_nodejs_gazelle//:defs.bzl", "ts_definition")
load("//:defs.bzl", "js_library")

ts_definition(
    name = "remark-html.d",
    srcs = ["remark-html.d.ts"],
    visibility = ["//visibility:public"],
)
