load("//:defs.bzl", "web_asset")

web_asset(
    name = "global_css",
    srcs = ["global.css"],
    visibility = ["//visibility:public"],
)

web_asset(
    name = "index_css",
    srcs = ["index.css"],
    visibility = ["//visibility:public"],
)

web_asset(
    name = "utils_module_css",
    srcs = ["utils.module.css"],
    visibility = ["//visibility:public"],
)
